########################################
#              MagoLiopoli             #
#                 MLHub                #
#             By MagoLione             #
########################################

# There are fully supported color and format codes (starting with &).
# When you are using color or format codes wrap the string by "" or ''.
# After changing this file, you can reload the configs by "/mlhub reload" command, without reloading the server.

MLHub:
  # The name of the hub's world.
  hub-world-name: your-hub-world

  # Do you want to enable /hub command?
  # Default: true
  hub-command: true

  # Only if "hub-command" is true.
  # The TP method.
  # standard: using standard bukkit API.
  # multiverse: using Multiverse-Core spawn position.
  # essentials: using Essentials warps.
  hub-tp-engine: standard

  # Only if "hub-command" is true.
  # This teleports a player twice, so bypass the "last position" of Multiverse-Inventories.
  # It's recommended to enable this only if you use the "last position" of Multiverse-Inventories.
  # ATTENTION: If enabled, this may create lag in teleport.
  # Default: false
  hub-tp-bypass-last-position: false

  # Only if "hub-tp-engine" is essentials.
  # The name of your EssentialsX warp to the hub spawn point.
  hub-warp: your-hub-spawn-warp

  # The navigation item.
  # Default: compass
  navigation-item: compass

  # The display name of the navigation item ("default-name" for the default value).
  # Default: default-name
  navigation-name: default-name

  # The navigation item's lore.
  navigation-lore:
    - 'This is an example of lore!'
    - 'This is an another line!!'

  # The position of the navigation item.
  # "-1" for the first free slot.
  navigation-position: -1

  # The name of the inventory opened with the navigation item.
  inventory-name: 'Select the world!'

  # The size of the inventory.
  # It must be a multiple of 9 between 9 and 54.
  # Default: 27
  inventory-size: 27

  # The worlds to display in the inventory.
  worlds:

    # The name of the world (or the warp's one if you are using essentials as engine).
    # Can be random if the enabled option is false.
    example:

      # The name of the item used to teleport to the world.
      item-name: Example

      # The lore of the item.
      item-lore:
        - 'This is an example of lore!'
        - 'This is an another line!!'

      # The item
      item: grass_block

      # The block's position in the inventory (starting from 0)
      # "-1" for the first free slot (recommended).
      position: -1

      # Is the teleport enabled for this world?
      # Default: true
      enabled: true

      # Only if enabled is true.
      # The teleport method.
      # standard: using standard bukkit API.
      # multiverse: using Multiverse-Core spawn position.
      # essentials: using Essentials warps.
      engine: standard

      # Only if enabled is true.
      # This teleports a player twice, so bypass the "last position" of Multiverse-Inventories.
      # It's recommended to enable this only if you use the "last position" of Multiverse-Inventories.
      # ATTENTION: If enabled, this may create lag in teleport.
      # Default: false
      bypass-last-position: false