########################################
#              MagoLiopoli             #
#                 MLHub                #
#             By MagoLione             #
########################################

# There are fully supported color and format codes (starting with &).
# When you are using color or format codes wrap the string by "" or ''.
# After changing this file, you can reload the configs by "/mlhub reload" command, without reloading the server.

MLHub:
  # The name of the hub's world.
  hub-world-name: your-hub-world

  # Do you want to enable /hub command?
  hub-command: true

  # Only if "hub-command" is true.
  # The TP method.
  # standard: using standard bukkit API.
  # multiverse: using Multiverse-Core spawn position.
  # multiverse-lastLocation: using Multiverse-Core (use player last location if implemented with Multiverse).
  # essentials: using Essentials warps.
  hub-tp-engine: standard

  # Only if "hub-tp-engine" is essentials.
  # The name of your EssentialsX warp to the hub spawn point.
  hub-warp: your-hub-spawn-warp

  # The navigation item.
  navigation-item: compass

  # The display name of the navigation item ("default-name" for the default value).
  navigation-name: default-name

  # The navigation item's lore.
  navigation-lore:
    - 'This is an example of lore!'
    - 'This is an another line!!'

  # The position of the navigation item.
  # "-1" for the first free slot.
  navigation-position: -1

  # The name of the inventory opened with the navigation item.
  inventory-name: 'Select the world!'

  # The size of the inventory (default 27).
  # It must be a multiple of 9 between 9 and 54.
  inventory-size: 27

  # The worlds to display in the inventory.
  worlds:

    # The name of the world (or the warp's one if you are using essentials as engine).
    example:

      # The name of the item used to teleport to the world.
      item-name: Example

      # The lore of the item.
      item-lore:
        - 'This is an example of lore!'
        - 'This is an another line!!'

      # The item
      item: grass_block

      # The block's position in the inventory (starting from 0)
      # "-1" for the first free slot (recommended).
      position: -1

      # The TP method.
      # standard: using standard bukkit API.
      # multiverse: using Multiverse-Core spawn position.
      # multiverse-lastLocation: using Multiverse-Core (use player last location if implemented with Multiverse).
      # essentials: using Essentials warps.
      engine: standard